# services to enable
[grpc.services.gateway]
commit_share_to_storage_grant = true
commit_share_to_storage_ref = true
datagateway = "https://sciencemesh.softwaremind.com/iop/datagateway"
appprovidersvc = "iop-gateway:19000"
appregistry = "iop-gateway:19000"

[grpc.services.storageregistry]
[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/public" = {"address" = "iop-storageprovider-public:16000"}
"/home" = {"address" = "iop-storageprovider-home:17000"}
"/reva" = {"address" = "iop-storageprovider-reva:18000"}
"123e4567-e89b-12d3-a456-426655440000" = {"address" = "iop-storageprovider-reva:18000"}

[grpc.services.authprovider]
[grpc.services.authregistry]

[grpc.services.authregistry.drivers.static.rules]
basic = "localhost:19000"
publicshares = "localhost:16000"
#appauth = "localhost:15000"

[grpc.services.applicationauth]
[grpc.services.userprovider]
[grpc.services.usershareprovider]
[grpc.services.groupprovider]
[grpc.services.publicshareprovider]

[grpc.services.ocmcore]

[grpc.services.ocminvitemanager]
[grpc.services.ocmproviderauthorizer]
driver = "json"


[grpc.services.appregistry]
driver = "static"

[grpc.services.appregistry.static.rules]
"text/plain" = "iop-gateway:19000"
"application/vnd.oasis.opendocument.text" = "iop-gateway:19000"
"application/vnd.oasis.opendocument.spreadsheet" = "iop-gateway:19000"
"application/vnd.oasis.opendocument.presentation" = "iop-gateway:19000"

[grpc.services.appregistry.drivers.static]
mime_types = [
    {"mime_type" = "text/plain", "extension" = "txt", "name" = "Text file", "description" = "Text file", "allow_creation" = true},
    {"mime_type" = "text/markdown", "extension" = "md", "name" = "Markdown file", "description" = "Markdown file", "allow_creation" = true},
    {"mime_type" = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "extension" = "docx", "name" = "Microsoft Word", "description" = "Microsoft Word document", "allow_creation" = true},
    {"mime_type" = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "extension" = "xlsx", "name" = "Microsoft Excel", "description" = "Microsoft Excel document", "allow_creation" = true},
    {"mime_type" = "application/vnd.openxmlformats-officedocument.presentationml.presentation", "extension" = "pptx", "name" = "Microsoft PowerPoint", "description" = "Microsoft PowerPoint document", "allow_creation" = true},
    {"mime_type" = "application/vnd.oasis.opendocument.text", "extension" = "odt", "name" = "OpenDocument", "description" = "OpenDocument text document", "allow_creation" = true},
    {"mime_type" = "application/vnd.oasis.opendocument.spreadsheet", "extension" = "ods", "name" = "OpenSpreadsheet", "description" = "OpenDocument spreadsheet document", "allow_creation" = true},
    {"mime_type" = "application/vnd.oasis.opendocument.presentation", "extension" = "odp", "name" = "OpenPresentation", "description" = "OpenDocument presentation document", "allow_creation" = true},
    {"mime_type" = "application/vnd.jupyter", "extension" = "ipynb", "name" = "Jupyter Notebook", "description" = "Jupyter Notebook"}
]

#[grpc.services.appprovider]
#mime_types = ["text/plain"]
#driver = "wopi"
#app_provider_url = "iop-gateway:19000"

#[grpc.services.appprovider.drivers.wopi]
#iop_secret = "qwerty12345"
#wopi_url = "http://0.0.0.0:8880/"
#app_name = "Collabora"
#app_url = "http://meshapps-collabora-code:9980"

[http.services.metrics]
metrics_data_driver_type = "json"
metrics_data_location = "/var/tmp/reva/metrics/metricsdata.json"
metrics_record_interval = 5000

[http.services.datagateway]
[http.services.prometheus]
[http.services.ocmd]
[http.services.ocdav]
[http.services.ocs]
#[http.services.appprovider]
